/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.isen.Projet.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
dependencies {
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.15.0")
    implementation("com.squareup.okhttp3:okhttp:4.9.3")
    implementation("com.formdev:flatlaf:3.1.1") // 🔥 FlatLaf pour un look moderne
}

dependencies {
    implementation("org.jxmapviewer:jxmapviewer2:2.6")
}
dependencies {
    implementation("org.slf4j:slf4j-api:2.0.7")
    implementation("ch.qos.logback:logback-classic:1.4.7")
}
dependencies {
    implementation("com.formdev:flatlaf:3.2.1") // ✅ Pour le look & feel moderne
    implementation("org.slf4j:slf4j-api:2.0.7") // ✅ Logger
    implementation("ch.qos.logback:logback-classic:1.4.7") // ✅ Logback pour logs
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.15.0") // ✅ JSON Parsing
    implementation("com.squareup.okhttp3:okhttp:4.10.0") // ✅ Pour les requêtes HTTP
}
dependencies {
    implementation("com.github.kittinunf.fuel:fuel:2.3.1") // ✅ Fuel pour les requêtes HTTP
    implementation("com.github.kittinunf.fuel:fuel-gson:2.3.1") // ✅ Désérialisation JSON avec Gson
    implementation("com.google.code.gson:gson:2.9.0") // ✅ Gson pour parser les JSON
}

